### ISSUE TITLE
ValueError: Expected object or value

### ISSUE THREAD

**Issue by GamJaChips** [SaidBySolo/neispy#25]
name = '홍천중학교'
scinfo = await neis.schoolInfo(SCHUL_NM=name,rawdata=True)

오늘 오후 까지는 정상이였는데 현재는 비동기로 해당 코드로 실행하면 해당 에러가 나옵니다.
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "d:\중요\Desktop\xxx\cogs\meal.py", line 225, in school_search
    scinfo = await neis.schoolInfo(SCHUL_NM=name,rawdata=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\neispy\asyncclient.py", line 99, in schoolInfo
    data = await self.http.schoolInfo(query)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\neispy\asynchttp.py", line 78, in schoolInfo
    return await self.request("get", "schoolInfo", query)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\neispy\asynchttp.py", line 38, in request
    data = ujson.loads(response)
ValueError: Expected object or value

**Comment by SaidBySolo** [comment]
https://open.neis.go.kr/503.html

api서버 문제이네요.

상태코드로도 서버상태를 핸들할수있게 하도록 수정하겠습니다.

**Comment by SaidBySolo** [comment]
상태 코드 대신 json으로 변환불가시 예외처리하였습니다.

해당 픽스는 2.0.5버전부터 적용됩니다.

**Comment by SaidBySolo** [comment]
2.0.6버전에 적용됬습니다.
